### PR TITLE
Search page

### PR DESCRIPTION
**Pull request by SamDepardieu**
# TODO:
~Finish the PR description~
Add the search backend function to the page

# Description

This PR brings up the search into policy docs content for the policytool website. 

## Type of change

Please delete options that are not relevant.

- [x] :sparkles: New feature

### CODE REVIEW

**Comment by hblanks** [comment]
@SamDepardieu  - should we be merging this?

**Comment by SamDepardieu** [comment]
This is only the frontend, no backend is implemented in this PR. Do you feel like it's still worth merging? If so, I'm happy to merge

**Comment by hblanks** [comment]
Unless it's broken what we have so far, we should probably merge.

**Comment by SamDepardieu** [comment]
Alright then, just need an approval 👍

**Pull request merged**
